### ISSUE TITLE
Priorities.

### ISSUE THREAD

**Issue by TheUpfinity** [UpFinityCrypto/UpFinityCrypto.github.io#13]
1. Swap sells
2. Tokenomics to: 9.5% lp 1% buyback 3% rewards 4% marketing & development 3% eco 1%redistribution/burn/etc
3. CB to: CB change to 4% buy and 8% trigger -> 2h duration
4. Exact countdown counter on dashboard for CB
5. 1 of the NFT pictures not displaying on website
6.  Swap display already the amount you will get after taxes. Avoids people feeling ripped off. They get what they saw they were going to get.
7. etc

**Comment by AllCoinLab** [comment]
separate it to multiple issues to track and thread each of them
