### ISSUE TITLE
Funds

### ISSUE THREAD

**Issue by TheUpfinity** [UpFinityCrypto/UpFinityCrypto.github.io#15]
2.5 bnb for:

1bnb -> 48h poocoin ads
1.5bnb -> Website design, website development, game ui , game sound effects, game music, animations for everything, nft avatar ui, other marketing (2 shillers), sweepwidget membership,  facebook ads (already paid for), etc

**Comment by AllCoinLab** [comment]
list each of them as a divided description.
1.5bnb -> Website design, website development, game ui , game sound effects, game music, animations for everything, nft avatar ui, other marketing (2 shillers), sweepwidget membership, facebook ads (already paid for), etc

**Comment by AllCoinLab** [comment]
1bnb sent for poocoin

**Comment by TheUpfinity** [comment]
...

Website design 0.13 bnb
 website development 0.13 bnb
  game ui 0.13 bnb
   game sound effects 0.13 bnb
    game music 0.13 bnb
     animations for everything 0.13  bnb
     nft avatar ui 0.13bnb
     other marketing (2 shillers) 0.13  bnb
     sweepwidget membership 0.13 bnb
      facebook ads (already paid for)  0.13  bnb
      etc 0.13 bnb

**Comment by AllCoinLab** [comment]
why each of them has same price?
write down details including which address / username gets that amount

**Comment by AllCoinLab** [comment]
and also, sum is not 1.5 bnb

**Comment by TheUpfinity** [comment]
Hire a an accountant or a CPA bookkeeper because just thinking about doing what you ask me gives me a headache.  And ofc none of that stuff will get done.

**Comment by AllCoinLab** [comment]
done
