### ISSUE TITLE
NFT border

### ISSUE THREAD

**Issue by TheUpfinity** [UpFinityCrypto/UpFinityCrypto.github.io#2]
![image](https://user-images.githubusercontent.com/95709913/145451590-8e45f9ff-2593-4479-8dd7-21c8440ce842.png)
padding to 0 and color of neon shadow for legendary to: #F9580C and epic to: #A7288A

**Comment by UpFinityCrypto** [comment]
> ![image](https://user-images.githubusercontent.com/95709913/145451590-8e45f9ff-2593-4479-8dd7-21c8440ce842.png) padding to 0 and color of neon shadow for legendary to: #F9580C and epic to: #A7288A

check
