### ISSUE TITLE
Website Update 12/09

### ISSUE THREAD

**Issue by TheUpfinity** [UpFinityCrypto/UpFinityCrypto.github.io#3]
![image](https://user-images.githubusercontent.com/95709913/145516755-e4722a79-06f3-479d-befc-ac2ca3885a8c.png)

NFT green glowing border change padding to 0, make color of epic purple and legendary orange

fix NFT display on "My NFT" and display on metamask wallet

Team section

**Comment by UpFinityCrypto** [comment]
fix NFT display on "My NFT" and display on metamask wallet - rephrase
others done check
