### ISSUE TITLE
NFT display on metamask and My NFT and when click on image on website

### ISSUE THREAD

**Issue by TheUpfinity** [UpFinityCrypto/UpFinityCrypto.github.io#9]
Fix:

NFT display on metamask wallet "NFT" section 

 NFT display on "My NFT"
 
 NFT display when clicked on image on website, epic should show epic with border, legendary should show new legendary with border

**Comment by UpFinityCrypto** [comment]
NFT display on metamask wallet "NFT" section => not showing?
NFT display on "My NFT" => ss
NFT display when clicked on image on website, epic should show epic with border, legendary should show new legendary with border => when isa make border + gif, then will fix altogether
